[package]
name = "cg-practicum"
version = "0.1.0"
edition = "2018"
authors = ["Bo Kleynen <kleynenbo@gmail.com>"]
repository = "https://github.com/BoKleynen/cg-practicum"
readme = "README.md"
description = """
Computer Graphics: Project (academic year 2020-2021)
"""

[dependencies]
clap = "3.0.0-beta.2"
rayon = "1.5"
image = "0.23"
nalgebra = "0.26"
itertools = "0.10"
chrono = "0.4"
rand = "0.8"

[profile.release]
lto = true

[features]
default = ["bvh"]

bvh = []
