[package]
name = "cg-practicum"
version = "0.1.0"
edition = "2018"
authors = ["Bo Kleynen <kleynenbo@gmail.com>"]
repository = "https://github.com/BoKleynen/cg-practicum"
readme = "README.md"
description = """
Computer Graphics: Project (academic year 2020-2021)
"""

[dependencies]
chrono = "0.4"
clap = "3.0.0-beta.2"
image = "0.23"
indicatif = { version = "0.16", features = ["rayon"] }
itertools = "0.10"
nalgebra = "0.26"
rand = "0.8"
rand_chacha = "0.3"
rand_distr = "0.4"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
lto = true

[features]
default = ["bvh"]

bvh = []
