[package]
name = "cg-practicum"
version = "0.1.0"
edition = "2018"
authors = ["Bo Kleynen <kleynenbo@gmail.com>"]
repository = "https://github.com/BoKleynen/cg-practicum"
readme = "README.md"
description = """
Computer Graphics: Project (academic year 2020-2021)
"""

[dependencies]
clap = "3.0.0-beta.2"
rayon = "1.5.0"
image = "0.23.13"
nalgebra = "0.24.1"

[profile.release]
lto = true
